class SofaStats:
    Individual_Stats = [
        "totalPass",
        "accuratePass",
        "totalLongBalls",
        "accurateLongBalls",
        "goalAssist",
        "totalCross",
        "accurateCross",
        "aerialLost",
        "aerialWon",
        "duelLost",
        "duelWon",
        "challengeLost",
        "dispossessed",
        "totalContest",
        "wonContest",
        "shotOffTarget",
        "onTargetScoringAttempt",
        "goals",
        "totalClearance",
        "outfielderBlock",
        "interceptionWon",
        "totalTackle",
        "errorLeadToAShot",
        "ownGoals",
        "wasFouled",
        "fouls",
        "totalOffside",
        "goodHighClaim",
        "saves",
        "totalKeeperSweeper",
        "accurateKeeperSweeper",
        "totalOffside",
        "minutesPlayed",
        "touches",
        "rating",
        "possessionLostCtrl",
        "expectedGoals",
        "keyPass",
        "expectedAssists",
    ]
    
    Team_Stats_For_Tournament = [
        "goalsScored",
        "goalsConceded",
        "assists",
        "shots",
        "penaltyGoals",
        "penaltiesTaken",
        "successfulDribbles",
        "dribbleAttempts",
        "corners",
        "averageBallPossession",
        "totalPasses",
        "accuratePasses",
        "accuratePassesPercentage",
        "totalLongBalls",
        "accurateLongBalls",
        "accurateLongBallsPercentage",
        "totalCrosses",
        "accurateCrosses",
        "accurateCrossesPercentage",
        "cleanSheets",
        "interceptions",
        "saves",
        "errorsLeadingToShot",
        "totalDuels",
        "duelsWon",
        "duelsWonPercentage",
        "totalAerialDuels",
        "aerialDuelsWon",
        "aerialDuelsWonPercentage",
        "offsides",
        "fouls",
        "yellowCards",
        "yellowRedCards",
        "redCards",
        "shotsAgainst",
        "goalKicks",
        "ballRecovery",
        "freeKicks",
        "matches",
        "awardedMatches",
    ]

    Player_Stats_For_Tournament = [
        "rating",
        "goals",
        "goalsAssistsSum",
        "accuratePasses",
        "inaccuratePasses",
        "totalPasses",
        "accuratePassesPercentage",
        "accurateFinalThirdPasses",
        "keyPasses",
        "successfulDribbles",
        "successfulDribblesPercentage",
        "interceptions",
        "yellowCards",
        "directRedCards",
        "redCards",
        "accurateCrosses",
        "accurateCrossesPercentage",
        "totalShots",
        "shotsOnTarget",
        "shotsOffTarget",
        "aerialDuelsWon",
        "aerialDuelsWonPercentage",
        "totalDuelsWon",
        "totalDuelsWonPercentage",
        "minutesPlayed",
        "goalConversionPercentage",
        "penaltiesTaken",
        "penaltyGoals",
        "shotFromSetPiece",
        "accurateLongBalls",
        "accurateLongBallsPercentage",
        "clearances",
        "errorLeadToShot",
        "wasFouled",
        "fouls",
        "dribbledPast",
        "offsides",
        "blockedShots",
        "passToAssist",
        "saves",
        "cleanSheet",
        "crossesNotClaimed",
        "matchesStarted",
        "penaltyConversion",
        "totalCross",
        "duelLost",
        "aerialLost",
        "attemptPenaltyMiss",
        "totalLongBalls",
        "goalsConceded",
        "scoringFrequency",
        "yellowRedCards",
        "substitutionsIn",
        "substitutionsOut",
        "goalKicks",
        "ballRecovery",
        "appearances",
    ]

    Match_Stats = [
        "Expected goals",
        "Ball possession",
        "Total shots",
        "Shots on target",
        "Shots off target",
        "Blocked shots",
        "Corner kicks",
        "Offsides",
        "Fouls",
        "Yellow cards",
        "Red cards",
        "Free kicks",
        "Throw-ins",
        "Goal kicks",
        "Hit woodwork",
        "Counter attacks",
        "Shots inside box",
        "Shots outside box",
        "Goalkeeper saves",
        "Passes",
        "Accurate passes",
        "Long balls",
        "Crosses",
        "Dribbles",
        "Possession lost",
        "Duels won",
        "Aerials won",
        "Tackles",
        "Interceptions",
        "Clearances",
    ]
    