class SofaStats:
    Individual_Stats = [
        "totalPass",
        "accuratePass",
        "totalLongBalls",
        "accurateLongBalls",
        "goalAssist",
        "totalCross",
        "accurateCross",
        "aerialLost",
        "aerialWon",
        "duelLost",
        "duelWon",
        "challengeLost",
        "dispossessed",
        "totalContest",
        "wonContest",
        "shotOffTarget",
        "onTargetScoringAttempt",
        "goals",
        "totalClearance",
        "outfielderBlock",
        "interceptionWon",
        "totalTackle",
        "errorLeadToAShot",
        "ownGoals",
        "wasFouled",
        "fouls",
        "totalOffside",
        "goodHighClaim",
        "saves",
        "totalKeeperSweeper",
        "accurateKeeperSweeper",
        "totalOffside",
        "minutesPlayed",
        "touches",
        "rating",
        "possessionLostCtrl",
        "expectedGoals",
        "keyPass",
        "expectedAssists",
    ]

    Num_Individual_Stats = len(Individual_Stats)
